### ISSUE TITLE
Biome Makeover ancient log and recipe error

### ISSUE THREAD

**Issue by DadoIrie** [JieningYu/CreatePlus#10]
title says everything XD
here's the uploaded log and note that all mods are disabled except for fabric api, create, createplus & biome makeover

[https://mclo.gs/0KLvPYY](https://mclo.gs/0KLvPYY)

**Comment by JieningYu** [comment]
oww

**Comment by JieningYu** [comment]
fixed

**Comment by DadoIrie** [comment]
would be appreciated if that gets fixed in the mod version (using 1.18.2)
[https://modrinth.com/mod/createplus/versions](https://modrinth.com/mod/createplus/versions)

**Comment by JieningYu** [comment]
emm i didn't and probably won't update this mod on modrinth or curseforge now.

**Comment by JieningYu** [comment]
but you can download this repo as zip and add to your world as datapack to replace the mod version of createplus's data.
