### ISSUE TITLE
Why a quilt mod instead of a fabric mod?

### ISSUE THREAD

**Issue by maximumpower55** [JieningYu/CreatePlus#5]
@JieningYu I like quilt and all, but i just can't get why you made this a quilt only mod instead of a fabric mod (that works on fabric and quilt)
Most users of create fabric use fabric, also a lot of people need this for big fabric modpacks, that can't be switched to quilt yet

**Comment by JieningYu** [comment]
Considering.

**Comment by JieningYu** [comment]
Also this repo is for CreatePlus Datapack which can be used for both Fabric and Quilt.

**Comment by maximumpower55** [comment]
> Also this repo is for CreatePlus Datapack which can be used for both Fabric and Quilt.

Last time i used the datapack standalone, it couldn't load because it couldn't find create:raw_zinc

**Comment by JieningYu** [comment]
> > Also this repo is for CreatePlus Datapack which can be used for both Fabric and Quilt.
> 
> Last time i used the datapack standalone, it couldn't load because it couldn't find create:raw_zinc

But actually create:raw_zinc exists in the game. Why you couldn't load?

**Comment by JieningYu** [comment]
I can load on my side.

**Comment by JieningYu** [comment]
Idk why I want to do all the things using QSL but not Fabric API. That seems to be the answer.

**Comment by maximumpower55** [comment]
> Idk why I want to do all the things using QSL but not Fabric API. That seems to be the answer.

😕

**Comment by JieningYu** [comment]
however a fabric version is planned

**Comment by maximumpower55** [comment]
> however a fabric version is planned

Great! Will love to use this in my personal modpack

**Comment by JieningYu** [comment]
@maximumpower55 Fabric version out now
