### ISSUE TITLE
Hidden Create Forge Dependancy?

### ISSUE THREAD

**Issue by DemonSlayer112** [JieningYu/CreatePlus#6]
Hello!
First off what exactly does this mod do? Im slighty confused in what it's doing in compatibility.
But it seems to download Create(Forge) with its install on the curseforge app:
![image](https://user-images.githubusercontent.com/70122500/169434284-988f90c3-faf1-4b9e-9bde-1a595c55a6d8.png)

Does it require this for fabric?

**Comment by JieningYu** [comment]
Convert Forge Tags to Fabric Tags; Add more recipes& crushed metal ores & compat items with other mods. For the details you can check the source code.
It's weird that it downloads the Create Forge (why? Anyway you can delete Create Forge.
<img width="608" alt="image" src="https://user-images.githubusercontent.com/61787533/169437626-f4ea1b40-4764-4cf1-9a49-0ed05aa34f3e.png">

**Comment by JieningYu** [comment]
Yes this requires Fabric Create.
