### ISSUE TITLE
AE2 supported recipe bug

### ISSUE THREAD

**Issue by KuroPeach** [JieningYu/CreatePlus#7]
AE2 supported recipe bug，The three chips are all synthesized to calculation chips。The problem is in the second step。
It is recommended to change the substrate to the corresponding chip board instead of the silicon board。
![%5T7@1IQPC`_NP5N8X81K{L](https://user-images.githubusercontent.com/19620848/173222090-dea9164b-c3f9-44ea-a322-0ea27854c469.png)
![Z)FN)KLNK8HK1S9~RY)O0_E](https://user-images.githubusercontent.com/19620848/173222097-7a3c25ea-6fbe-4774-be28-95c2be99d4c0.png)

**Comment by JieningYu** [comment]
ok i know

**Comment by JieningYu** [comment]
probably fixed now
to use the fixed version, download this repo and unarchive it into your "datapacks" folder and reload game.
